"""
catalogue_loader.py — Load and query L+G meter object catalogues.

Catalogues are dictionaries describing every short code (object address)
exposed by a meter variant, generated by tools/build_catalogues.py from
the official L+G XML files.

The expected file layout is a Python module exporting one dict:

    CATALOGUES: dict[str, dict[int, tuple[str, int, str]]] = {
        "B32": {
            0x3848: ("StringRegisterConfigId", 2, "VisibleString"),
            0x5A88: ("StringRegisterID2_1",    2, "VisibleString"),
            ...
        },
        ...
    }

  outer key   = software ID returned by the meter (FF08 read)
  inner key   = short code / attribute address
  inner value = (object_name, attribute_index, field_type)


Default location:  ~/.dlms_meter/catalogues.py
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


DEFAULT_CATALOGUE_PATH = Path.home() / ".dlms_meter" / "catalogues.py"

# Module-level cache so repeated load_catalogues() calls don't re-import
_catalogues: dict[str, dict[int, tuple[str, int, str]]] | None = None


def load_catalogues(path: Path | str | None = None) -> dict:
    """
    Load the catalogues from a Python file.

    Args:
        path: optional path to a catalogues.py file. Defaults to
              ~/.dlms_meter/catalogues.py.

    Returns:
        The CATALOGUES dict.

    Raises:
        FileNotFoundError: if no catalogue file is found.
        AttributeError:    if the file doesn't expose a CATALOGUES dict.
    """
    global _catalogues

    target = Path(path) if path else DEFAULT_CATALOGUE_PATH
    if not target.exists():
        raise FileNotFoundError(
            f"No catalogue file at {target}. "
            f"Generate one with `python -m dlms_meter.tools.build_catalogues "
            f"/path/to/xml_dir/`"
        )

    spec = importlib.util.spec_from_file_location("dlms_meter_catalogues", target)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load catalogue module from {target}")

    module = importlib.util.module_from_spec(spec)
    sys.modules["dlms_meter_catalogues"] = module
    spec.loader.exec_module(module)

    if not hasattr(module, "CATALOGUES"):
        raise AttributeError(
            f"{target} does not expose a CATALOGUES dict. Did the build "
            f"step finish correctly?"
        )

    _catalogues = module.CATALOGUES
    return _catalogues


def get_catalogues() -> dict | None:
    """Return the currently loaded catalogues, or None if not loaded yet."""
    return _catalogues


def get_catalogue(variant: str) -> dict[int, tuple[str, int, str]] | None:
    """
    Return the catalogue for one variant (e.g. 'B32'), or None if absent.

    Triggers an auto-load on first call.
    """
    cats = get_catalogues()
    if cats is None:
        try:
            cats = load_catalogues()
        except (FileNotFoundError, ImportError, AttributeError):
            return None
    return cats.get(variant)


def resolve_address(variant: str, target: str | int) -> int | None:
    """
    Resolve a friendly name or raw int into a short-code address using the
    given variant's catalogue.

    Args:
        variant: software ID e.g. 'B32'
        target:  either a raw int (returned as-is) or an object name
                 (e.g. 'StringRegisterID2_1' or a friendly alias).

    Returns:
        The 16-bit address, or None if not found.
    """
    if isinstance(target, int):
        return target

    cat = get_catalogue(variant)
    if cat is None:
        return None

    # First try as official L+G name
    for addr, (name, _attr, _ftype) in cat.items():
        if name == target:
            return addr

    # Then try friendly aliases
    from .vendors.landis_gyr_aliases import ALIASES
    official = ALIASES.get(target)
    if official is not None:
        for addr, (name, _attr, _ftype) in cat.items():
            if name == official:
                return addr

    return None


def describe(variant: str, address: int) -> tuple[str, int, str] | None:
    """
    Look up an address in a catalogue. Returns (name, attribute, field_type)
    or None if the address isn't known.
    """
    cat = get_catalogue(variant)
    if cat is None:
        return None
    return cat.get(address)
