"""
catalogue_loader.py — Load and query L+G meter object catalogues.

Catalogues are dictionaries describing every short code (object address)
exposed by a meter variant, generated by tools/build_catalogues.py from
the official L+G XML files.

The expected file layout is a Python module exporting one dict:

    CATALOGUES: dict[str, dict[int, tuple[str, int, str]]] = {
        "B32": {
            0x3848: ("StringRegisterConfigId", 2, "VisibleString"),
            0x5A88: ("StringRegisterID2_1",    2, "VisibleString"),
            ...
        },
        ...
    }

  outer key   = software ID returned by the meter (FF08 read)
  inner key   = short code / attribute address
  inner value = (object_name, attribute_index, field_type)


Search order (load_catalogues() with no argument):
  1. $DLMS_METER_CATALOGUES environment variable
  2. catalogues.py next to the dlms_meter package
  3. ~/.dlms_meter/catalogues.py
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path


# Search locations for the catalogue file, in priority order.
# load_catalogues() tries each in turn and uses the first one that exists.
PACKAGE_DIR        = Path(__file__).resolve().parent
PACKAGE_CATALOGUES = PACKAGE_DIR / "catalogues.py"
USER_CATALOGUES    = Path.home() / ".dlms_meter" / "catalogues.py"

# Environment variable that, if set, overrides the search order
ENV_VAR = "DLMS_METER_CATALOGUES"

# Module-level cache so repeated load_catalogues() calls don't re-import
_catalogues: dict[str, dict[int, tuple[str, int, str]]] | None = None
_loaded_from: Path | None = None


def _find_catalogue_path() -> Path | None:
    """
    Resolve the catalogue path using the priority search order.

    Order:
      1. $DLMS_METER_CATALOGUES (environment variable)
      2. <package>/catalogues.py  (next to the dlms_meter package)
      3. ~/.dlms_meter/catalogues.py  (user home directory)

    Returns None if no path exists.
    """
    env_path = os.environ.get(ENV_VAR)
    if env_path:
        p = Path(env_path)
        if p.exists():
            return p

    for candidate in (PACKAGE_CATALOGUES, USER_CATALOGUES):
        if candidate.exists():
            return candidate

    return None


def load_catalogues(path: Path | str | None = None) -> dict:
    """
    Load the catalogues from a Python file.

    Search order if no path is given:
      1. $DLMS_METER_CATALOGUES environment variable
      2. catalogues.py next to the dlms_meter package
      3. ~/.dlms_meter/catalogues.py

    Args:
        path: optional explicit path to a catalogues.py file.

    Returns:
        The CATALOGUES dict.

    Raises:
        FileNotFoundError: if no catalogue file is found.
        AttributeError:    if the file doesn't expose a CATALOGUES dict.
    """
    global _catalogues, _loaded_from

    if path is not None:
        target = Path(path)
        if not target.exists():
            raise FileNotFoundError(f"No catalogue file at {target}")
    else:
        target = _find_catalogue_path()
        if target is None:
            searched = [
                f"  - ${ENV_VAR} (env var, not set)" if not os.environ.get(ENV_VAR)
                else f"  - ${ENV_VAR}={os.environ[ENV_VAR]} (does not exist)",
                f"  - {PACKAGE_CATALOGUES}",
                f"  - {USER_CATALOGUES}",
            ]
            raise FileNotFoundError(
                "No catalogue file found. Searched:\n"
                + "\n".join(searched)
                + "\nGenerate one with: python tools/build_catalogues.py /path/to/xml_dir/"
            )

    spec = importlib.util.spec_from_file_location("dlms_meter_catalogues", target)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load catalogue module from {target}")

    module = importlib.util.module_from_spec(spec)
    sys.modules["dlms_meter_catalogues"] = module
    spec.loader.exec_module(module)

    if not hasattr(module, "CATALOGUES"):
        raise AttributeError(
            f"{target} does not expose a CATALOGUES dict. Did the build "
            f"step finish correctly?"
        )

    _catalogues  = module.CATALOGUES
    _loaded_from = target
    return _catalogues


def loaded_from() -> Path | None:
    """Path of the catalogue file currently loaded, or None if not loaded."""
    return _loaded_from


def get_catalogues() -> dict | None:
    """Return the currently loaded catalogues, or None if not loaded yet."""
    return _catalogues


def get_catalogue(variant: str) -> dict[int, tuple[str, int, str]] | None:
    """
    Return the catalogue for one variant (e.g. 'B32'), or None if absent.

    Triggers an auto-load on first call.
    """
    cats = get_catalogues()
    if cats is None:
        try:
            cats = load_catalogues()
        except (FileNotFoundError, ImportError, AttributeError):
            return None
    return cats.get(variant)


def resolve_address(variant: str, target: str | int) -> int | None:
    """
    Resolve a friendly name or raw int into a short-code address using the
    given variant's catalogue.

    Args:
        variant: software ID e.g. 'B32'
        target:  either a raw int (returned as-is) or an object name
                 (e.g. 'StringRegisterID2_1' or a friendly alias).

    Returns:
        The 16-bit address, or None if not found.
    """
    if isinstance(target, int):
        return target

    cat = get_catalogue(variant)
    if cat is None:
        return None

    # First try as official L+G name
    for addr, (name, _attr, _ftype) in cat.items():
        if name == target:
            return addr

    # Then try friendly aliases
    from .vendors.landis_gyr_aliases import ALIASES
    official = ALIASES.get(target)
    if official is not None:
        for addr, (name, _attr, _ftype) in cat.items():
            if name == official:
                return addr

    return None


def describe(variant: str, address: int) -> tuple[str, int, str] | None:
    """
    Look up an address in a catalogue. Returns (name, attribute, field_type)
    or None if the address isn't known.
    """
    cat = get_catalogue(variant)
    if cat is None:
        return None
    return cat.get(address)
