"""
build_catalogues.py — Convert L+G ObjectList_*.xml files to Python dicts.

These XML files come with official L+G software and describe, for each
firmware variant, the full mapping of short codes to object names, attributes,
and data types. We don't redistribute them (licensing); each user runs this
script once against their own copy.

Usage:
    python tools/build_catalogues.py path/to/xml_dir/  [output_path]

Output: a single Python file containing one dict per processed XML.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import NamedTuple


NS = {"ns": "http://tempuri.org/DeviceDescriptionDataSet.xsd"}


class CatalogueEntry(NamedTuple):
    """A single entry in a meter object catalogue."""
    address:    int        # short code: 2-byte attribute address (what goes on the wire)
    name:       str        # human-readable name, e.g. "StringRegisterConfigId"
    attribute:  int        # attribute index, almost always 2 ("CurrentValue")
    field_type: str        # raw XML field type, e.g. "VisibleString", "RegisterValueInt32"


def parse_catalogue_file(path: Path) -> tuple[str, list[CatalogueEntry]]:
    """
    Parse one ObjectList_*.xml file.

    Returns:
        (variant_name, entries)  where variant_name is e.g. "B30" and entries
        is the list of all readable attributes.
    """
    tree    = ET.parse(path)
    root    = tree.getroot()
    dd_node = root.find("ns:DDs", NS)
    if dd_node is None:
        raise ValueError(f"{path}: no DDs element found")

    variant = dd_node.get("DDFirmware") or path.stem.replace("ObjectList_", "")
    prefix  = f"{dd_node.get('DDName')}."

    entries: list[CatalogueEntry] = []
    for obj in dd_node.findall("ns:Objects", NS):
        obj_name = obj.get("ObjectName", "").removeprefix(prefix)

        for attr in obj.findall("ns:Attributes", NS):
            attr_idx_str = attr.get("AttributeIndex")
            if attr_idx_str is None:
                continue
            attr_idx  = int(attr_idx_str)
            addr_str  = attr.get("AttributeAddress")
            if addr_str is None:
                continue
            addr = int(addr_str, 16)

            field = attr.find("ns:Fields", NS)
            ftype = field.get("FieldType") if field is not None else "?"

            entries.append(CatalogueEntry(
                address=addr,
                name=obj_name,
                attribute=attr_idx,
                field_type=ftype,
            ))

    return variant, entries


def render_python(catalogues: dict[str, list[CatalogueEntry]]) -> str:
    """Render parsed catalogues as a Python module."""
    lines = [
        '"""',
        'landis_gyr_catalogues.py — L+G meter object catalogues.',
        "",
        "Auto-generated by tools/build_catalogues.py from official L+G XML files.",
        "Do not edit by hand. Re-run the converter to update.",
        "",
        "Format:",
        "    CATALOGUES = {",
        '        "B30": {',
        '            0x3848: ("StringRegisterConfigId",     2, "VisibleString"),',
        "            ...",
        "        },",
        "        ...",
        "    }",
        "",
        "Indexed by short-code (attribute address). Each entry is a tuple:",
        "    (object_name, attribute_index, field_type)",
        '"""',
        "",
        "CATALOGUES: dict[str, dict[int, tuple[str, int, str]]] = {",
    ]

    for variant in sorted(catalogues):
        entries = catalogues[variant]
        # Only keep attribute index 2 (CurrentValue) — that's the readable value.
        # Other indexes (5, 6 = access list, id string) are protocol metadata.
        value_entries = [e for e in entries if e.attribute == 2]
        # Sort by address for stable diffs
        value_entries.sort(key=lambda e: e.address)

        lines.append(f'    "{variant}": {{')
        for e in value_entries:
            lines.append(
                f'        0x{e.address:04X}: '
                f'("{e.name}", {e.attribute}, "{e.field_type}"),'
            )
        lines.append("    },")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xml_dir", type=Path,
                   help="Directory containing ObjectList_*.xml files")
    p.add_argument("output", type=Path, nargs="?",
                   default=None,
                   help="Output Python file (default: catalogues.py inside "
                        "the dlms_meter package directory)")
    args = p.parse_args(argv)

    output_path = args.output
    if output_path is None:
        # Default: write next to the dlms_meter package, so the loader's
        # priority search finds it without any extra config.
        try:
            import dlms_meter
            pkg_dir = Path(dlms_meter.__file__).resolve().parent
            output_path = pkg_dir / "catalogues.py"
        except ImportError:
            # Fallback to the user-home location if the package isn't importable
            output_path = Path.home() / ".dlms_meter" / "catalogues.py"

    xml_files = sorted(args.xml_dir.glob("ObjectList_*.xml"))
    if not xml_files:
        print(f"No ObjectList_*.xml files found in {args.xml_dir}", file=sys.stderr)
        return 1

    catalogues = {}
    for xml in xml_files:
        try:
            variant, entries = parse_catalogue_file(xml)
        except Exception as e:
            print(f"  ✗ {xml.name}: {e}", file=sys.stderr)
            continue
        catalogues[variant] = entries
        print(f"  ✓ {xml.name}: variant {variant!r}, {len(entries)} attributes")

    if not catalogues:
        print("Nothing parsed; aborting.", file=sys.stderr)
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_python(catalogues), encoding="utf-8")

    total_attrs = sum(len(e) for e in catalogues.values())
    print(
        f"\nWrote {len(catalogues)} catalogues, "
        f"{total_attrs} total attributes → {output_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
